In [1]:
import pandas as pd

In [2]:
# Loading the final dataset

production = pd.read_csv(
    "../../data/processed/production_history_2021_2025.csv"
)

rainfall = pd.read_csv("../../data/processed/rainfall_features_2021_2025.csv")

In [3]:
production.head()

,State,District,Crop,Year,Area,Production,Yield,Year_Order,Years_ Available,Complete_4_year_history,Previous_Yield,Previous_yield_percentage,Previous_area,Previous_Area_Percentage,Previous_Production,Production_Change_Pct,History_avg_yield,Yield_Deviation_Pct
0,Haryana,Ambala,Maize,2021-22,0.00,0.01,3945.0,2021,4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Haryana,Ambala,Maize,2022-23,0.00,0.00,3455.0,2022,4,True,3945.0,-12.420786,0.0,NaN,0.01,-100.0,3945.0,-12.420786
2,Haryana,Ambala,Maize,2023-24,0.00,0.01,4642.0,2023,4,True,3455.0,34.356006,0.0,NaN,0.00,NaN,3700.0,25.459459
3,Haryana,Ambala,Maize,2024-25,0.00,0.00,3714.0,2024,4,True,4642.0,-19.991383,0.0,NaN,0.01,-100.0,4014.0,-7.473842
4,Haryana,Ambala,Rice,2021-22,0.94,3.86,4107.0,2021,4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
rainfall.head()

,State,District,Year,Crop_Year_Rainfall_mm,Rainy_Days,Heavy_Rain_Days,Days_Available,Monsoon_Rainfall_mm,Rabi_Rainfall_mm,Historical_Avg_Rainfall,Rainfall_Deviation_Pct
0,Haryana,Ambala,2021-22,1297.57,97,0,365,981.67,246.72,NaN,NaN
1,Haryana,Ambala,2022-23,1567.66,110,1,365,1207.36,181.25,1297.570000,20.815062
2,Haryana,Ambala,2023-24,1301.31,84,3,366,1120.44,152.26,1432.615000,-9.165407
3,Haryana,Ambala,2024-25,1447.69,111,1,365,1191.42,133.39,1388.846667,4.236849
4,Haryana,Bhiwani,2021-22,724.11,52,0,365,610.61,89.75,NaN,NaN

In [6]:
# Checking the years on both datasets

print("Production Years:")
print(production["Year"].value_counts().sort_index())

print("\nRainfall Years:")
print(rainfall["Year"].value_counts().sort_index())

Production Years:
Year
2021-22    353
2022-23    348
2023-24    347
2024-25    355
Name: count, dtype: int64

Rainfall Years:
Year
2021-22    120
2022-23    120
2023-24    120
2024-25    120
Name: count, dtype: int64

In [8]:
# Checking for rainfall duplicates before merging

rainfall_duplicates= rainfall.duplicated(
    subset=["State","District","Year"]).sum()

print(rainfall_duplicates)

0

In [9]:
rainfall.rename(columns={"Crop_year":"Year"} , inplace= True)

In [10]:
# Checking the production size

production.shape

(1403, 18)

In [11]:
# Performing the final merge

agri_data = production.merge(
    rainfall , on=["State","District","Year"],how="left")

In [12]:
# Checking the shape after merge

print("Before merge:",production.shape)
print("After merge:" , agri_data.shape)

Before merge: (1403, 18)
After merge: (1403, 26)

In [13]:
# Checking for missinf rainfall

agri_data["Crop_Year_Rainfall_mm"].isnull().sum()

np.int64(0)

In [14]:
agri_data[
    [
        "State",
        "District",
        "Crop",
        "Year",
        "Crop_Year_Rainfall_mm"
    ]
].head(20)

      State District   Crop     Year  Crop_Year_Rainfall_mm
0   Haryana   Ambala  Maize  2021-22                1297.57
1   Haryana   Ambala  Maize  2022-23                1567.66
2   Haryana   Ambala  Maize  2023-24                1301.31
3   Haryana   Ambala  Maize  2024-25                1447.69
4   Haryana   Ambala   Rice  2021-22                1297.57
5   Haryana   Ambala   Rice  2022-23                1567.66
6   Haryana   Ambala   Rice  2023-24                1301.31
7   Haryana   Ambala   Rice  2024-25                1447.69
8   Haryana   Ambala  Wheat  2021-22                1297.57
9   Haryana   Ambala  Wheat  2022-23                1567.66
10  Haryana   Ambala  Wheat  2023-24                1301.31
11  Haryana   Ambala  Wheat  2024-25                1447.69
12  Haryana  Bhiwani  Maize  2021-22                 724.11
13  Haryana  Bhiwani  Maize  2023-24                 449.71
14  Haryana  Bhiwani  Maize  2024-25                 803.10
15  Haryana  Bhiwani   Rice  2021-22                 724.11
16  Haryana  Bhiwani   Rice  2022-23                 692.25
17  Haryana  Bhiwani   Rice  2023-24                 449.71
18  Haryana  Bhiwani   Rice  2024-25                 803.10
19  Haryana  Bhiwani  Wheat  2021-22                 724.11

In [15]:
# Checking for problematic districts - Shrawasti and Shahid Bhagat Singh Nagar

agri_data[
    agri_data["District"].isin(
        [
            "Shrawasti",
            "Shahid Bhagat Singh Nagar"
        ]
    )
][
    [
        "State",
        "District",
        "Crop",
        "Year",
        "Crop_Year_Rainfall_mm"
    ]
]

,State,District,Crop,Year,Crop_Year_Rainfall_mm
473,Punjab,Shahid Bhagat Singh Nagar,Maize,2021-22,1060.59
474,Punjab,Shahid Bhagat Singh Nagar,Maize,2022-23,1359.03
475,Punjab,Shahid Bhagat Singh Nagar,Maize,2023-24,1308.70
476,Punjab,Shahid Bhagat Singh Nagar,Maize,2024-25,781.01
477,Punjab,Shahid Bhagat Singh Nagar,Rice,2021-22,1060.59
478,Punjab,Shahid Bhagat Singh Nagar,Rice,2022-23,1359.03
479,Punjab,Shahid Bhagat Singh Nagar,Rice,2023-24,1308.70
480,Punjab,Shahid Bhagat Singh Nagar,Rice,2024-25,781.01
481,Punjab,Shahid Bhagat Singh Nagar,Wheat,2021-22,1060.59
482,Punjab,Shahid Bhagat Singh Nagar,Wheat,2022-23,1359.03
483,Punjab,Shahid Bhagat Singh Nagar,Wheat,2023-24,1308.70
484,Punjab,Shahid Bhagat Singh Nagar,Wheat,2024-25,781.01
1319,Uttar Pradesh,Shrawasti,Maize,2021-22,1615.69
1320,Uttar Pradesh,Shrawasti,Maize,2022-23,1294.03
1321,Uttar Pradesh,Shrawasti,Maize,2023-24,1141.14
1322,Uttar Pradesh,Shrawasti,Maize,2024-25,1220.80
1323,Uttar Pradesh,Shrawasti,Rice,2021-22,1615.69
1324,Uttar Pradesh,Shrawasti,Rice,2022-23,1294.03
1325,Uttar Pradesh,Shrawasti,Rice,2023-24,1141.14
1326,Uttar Pradesh,Shrawasti,Rice,2024-25,1220.80
1327,Uttar Pradesh,Shrawasti,Wheat,2021-22,1615.69
1328,Uttar Pradesh,Shrawasti,Wheat,2022-23,1294.03
1329,Uttar Pradesh,Shrawasti,Wheat,2023-24,1141.14
1330,Uttar Pradesh,Shrawasti,Wheat,2024-25,1220.80

In [16]:
# Checking rainfall feature columns

agri_data.columns.tolist()

['State',
 'District',
 'Crop',
 'Year',
 'Area',
 'Production',
 'Yield',
 'Year_Order',
 'Years_ Available',
 'Complete_4_year_history',
 'Previous_Yield',
 'Previous_yield_percentage',
 'Previous_area',
 'Previous_Area_Percentage',
 'Previous_Production',
 'Production_Change_Pct',
 'History_avg_yield',
 'Yield_Deviation_Pct',
 'Crop_Year_Rainfall_mm',
 'Rainy_Days',
 'Heavy_Rain_Days',
 'Days_Available',
 'Monsoon_Rainfall_mm',
 'Rabi_Rainfall_mm',
 'Historical_Avg_Rainfall',
 'Rainfall_Deviation_Pct']

In [17]:
# Checking for any missing values

agri_data.isnull().sum()

State                          0
District                       0
Crop                           0
Year                           0
Area                           0
Production                     0
Yield                          0
Year_Order                     0
Years_ Available               0
Complete_4_year_history        0
Previous_Yield               360
Previous_yield_percentage    361
Previous_area                360
Previous_Area_Percentage     487
Previous_Production          360
Production_Change_Pct        448
History_avg_yield            360
Yield_Deviation_Pct          361
Crop_Year_Rainfall_mm          0
Rainy_Days                     0
Heavy_Rain_Days                0
Days_Available                 0
Monsoon_Rainfall_mm            0
Rabi_Rainfall_mm               0
Historical_Avg_Rainfall      353
Rainfall_Deviation_Pct       353
dtype: int64

In [18]:
# Checking manually for one district

agri_data[
    (agri_data["State"] == "Uttar Pradesh")
    &
    (agri_data["District"] == "Meerut")
][
    [
        "Crop",
        "Year",
        "Yield",
        "Crop_Year_Rainfall_mm",
        "Monsoon_Rainfall_mm",
        "Rabi_Rainfall_mm",
        "Rainfall_Deviation_Pct"
    ]
].sort_values(
    ["Crop", "Year"]
)

,Crop,Year,Yield,Crop_Year_Rainfall_mm,Monsoon_Rainfall_mm,Rabi_Rainfall_mm,Rainfall_Deviation_Pct
1151,Maize,2021-22,2151.0,1106.73,812.39,246.91,NaN
1152,Maize,2022-23,2024.0,936.84,604.92,247.36,-15.350628
1153,Maize,2023-24,2706.0,802.46,728.24,69.17,-21.464887
1154,Maize,2024-25,3463.0,1065.14,923.74,45.47,12.276399
1155,Rice,2021-22,2906.0,1106.73,812.39,246.91,NaN
1156,Rice,2022-23,2470.0,936.84,604.92,247.36,-15.350628
1157,Rice,2023-24,2537.0,802.46,728.24,69.17,-21.464887
1158,Rice,2024-25,2560.0,1065.14,923.74,45.47,12.276399
1159,Wheat,2021-22,4180.0,1106.73,812.39,246.91,NaN
1160,Wheat,2022-23,4282.0,936.84,604.92,247.36,-15.350628
1161,Wheat,2023-24,4210.0,802.46,728.24,69.17,-21.464887
1162,Wheat,2024-25,4049.0,1065.14,923.74,45.47,12.276399

In [19]:
print(rainfall.columns.tolist())

['State', 'District', 'Year', 'Crop_Year_Rainfall_mm', 'Rainy_Days', 'Heavy_Rain_Days', 'Days_Available', 'Monsoon_Rainfall_mm', 'Rabi_Rainfall_mm', 'Historical_Avg_Rainfall', 'Rainfall_Deviation_Pct']

In [20]:
print(agri_data.columns.tolist())

['State', 'District', 'Crop', 'Year', 'Area', 'Production', 'Yield', 'Year_Order', 'Years_ Available', 'Complete_4_year_history', 'Previous_Yield', 'Previous_yield_percentage', 'Previous_area', 'Previous_Area_Percentage', 'Previous_Production', 'Production_Change_Pct', 'History_avg_yield', 'Yield_Deviation_Pct', 'Crop_Year_Rainfall_mm', 'Rainy_Days', 'Heavy_Rain_Days', 'Days_Available', 'Monsoon_Rainfall_mm', 'Rabi_Rainfall_mm', 'Historical_Avg_Rainfall', 'Rainfall_Deviation_Pct']

## Building rainfall feature correctly

In [21]:
# Sort rainfall chronologically

year_order = {
    "2021-22": 2021,
    "2022-23": 2022,
    "2023-24": 2023,
    "2024-25": 2024
}

rainfall["Year_Order"] = rainfall["Year"].map(
    year_order
)

rainfall = rainfall.sort_values(
    [
        "State",
        "District",
        "Year_Order"
    ]
).reset_index(drop=True)

In [22]:
# Calculate historical average rainfall

rainfall[
    "Historical_Avg_Rainfall"
] = (
    rainfall
    .groupby(
        ["State", "District"]
    )["Crop_Year_Rainfall_mm"]
    .transform(
        lambda x:
        x.shift(1).expanding().mean()
    )
)

In [23]:
# Calculate rainfall deviation

import numpy as np

historical_rainfall_safe = (
    rainfall[
        "Historical_Avg_Rainfall"
    ]
    .replace(0, np.nan)
)

In [24]:
rainfall[
    "Rainfall_Deviation_Pct"
] = (
    (
        rainfall[
            "Crop_Year_Rainfall_mm"
        ]
        -
        rainfall[
            "Historical_Avg_Rainfall"
        ]
    )
    /
    historical_rainfall_safe
) * 100

In [25]:
# Checking the new columns

rainfall[
    [
        "State",
        "District",
        "Year",
        "Crop_Year_Rainfall_mm",
        "Historical_Avg_Rainfall",
        "Rainfall_Deviation_Pct"
    ]
].head(15)

,State,District,Year,Crop_Year_Rainfall_mm,Historical_Avg_Rainfall,Rainfall_Deviation_Pct
0,Haryana,Ambala,2021-22,1297.57,NaN,NaN
1,Haryana,Ambala,2022-23,1567.66,1297.570000,20.815062
2,Haryana,Ambala,2023-24,1301.31,1432.615000,-9.165407
3,Haryana,Ambala,2024-25,1447.69,1388.846667,4.236849
4,Haryana,Bhiwani,2021-22,724.11,NaN,NaN
5,Haryana,Bhiwani,2022-23,692.25,724.110000,-4.399884
6,Haryana,Bhiwani,2023-24,449.71,708.180000,-36.497783
7,Haryana,Bhiwani,2024-25,803.10,622.023333,29.110912
8,Haryana,Charkhi Dadri,2021-22,953.05,NaN,NaN
9,Haryana,Charkhi Dadri,2022-23,821.20,953.050000,-13.834531
10,Haryana,Charkhi Dadri,2023-24,483.28,887.125000,-45.522897
11,Haryana,Charkhi Dadri,2024-25,805.28,752.510000,7.012531
12,Haryana,Faridabad,2021-22,993.13,NaN,NaN
13,Haryana,Faridabad,2022-23,869.97,993.130000,-12.401196
14,Haryana,Faridabad,2023-24,742.72,931.550000,-20.270517

In [26]:
# Removing helper column

rainfall = rainfall.drop(
    columns=["Year_Order"]
)

In [27]:
# Save the corrected rainfall feature dataset
rainfall.to_csv(
    "../../data/processed/"
    "rainfall_features_2021_2025.csv",
    index=False
)

In [28]:
# Recreating the merge

agri_data = production.merge(
    rainfall,
    on=[
        "State",
        "District",
        "Year"
    ],
    how="left",
    validate="many_to_one"
)

In [29]:
# Checking the merge again
print("Production:", production.shape)
print("Merged:", agri_data.shape)

Production: (1403, 18)
Merged: (1403, 26)

In [30]:
print(
    "Missing rainfall:",
    agri_data[
        "Crop_Year_Rainfall_mm"
    ].isnull().sum()
)

Missing rainfall: 0

In [31]:
agri_data[
    "Rainfall_Deviation_Pct"
].isnull().sum()

np.int64(353)

In [43]:
if "Year_Order" in agri_data.columns:
    agri_data = agri_data.drop(
        columns=["Year_Order"]
    )

In [44]:
# Meerut-check

agri_data[
    (agri_data["State"] == "Uttar Pradesh")
    &
    (agri_data["District"] == "Meerut")
][
    [
        "Crop",
        "Year",
        "Yield",
        "Crop_Year_Rainfall_mm",
        "Monsoon_Rainfall_mm",
        "Rabi_Rainfall_mm",
        "Historical_Avg_Rainfall",
        "Rainfall_Deviation_Pct"
    ]
].sort_values(
    ["Crop", "Year"]
)

,Crop,Year,Yield,Crop_Year_Rainfall_mm,Monsoon_Rainfall_mm,Rabi_Rainfall_mm,Historical_Avg_Rainfall,Rainfall_Deviation_Pct
1151,Maize,2021-22,2151.0,1106.73,812.39,246.91,NaN,NaN
1152,Maize,2022-23,2024.0,936.84,604.92,247.36,1106.730000,-15.350628
1153,Maize,2023-24,2706.0,802.46,728.24,69.17,1021.785000,-21.464887
1154,Maize,2024-25,3463.0,1065.14,923.74,45.47,948.676667,12.276399
1155,Rice,2021-22,2906.0,1106.73,812.39,246.91,NaN,NaN
1156,Rice,2022-23,2470.0,936.84,604.92,247.36,1106.730000,-15.350628
1157,Rice,2023-24,2537.0,802.46,728.24,69.17,1021.785000,-21.464887
1158,Rice,2024-25,2560.0,1065.14,923.74,45.47,948.676667,12.276399
1159,Wheat,2021-22,4180.0,1106.73,812.39,246.91,NaN,NaN
1160,Wheat,2022-23,4282.0,936.84,604.92,247.36,1106.730000,-15.350628
1161,Wheat,2023-24,4210.0,802.46,728.24,69.17,1021.785000,-21.464887
1162,Wheat,2024-25,4049.0,1065.14,923.74,45.47,948.676667,12.276399

In [45]:
# Saving the merged dataset

agri_data.to_csv(
    "../../data/processed/"
    "production_rainfall_merged_2021_2025.csv",
    index=False
)

In [46]:
# Testing the merge file 

test_merge = pd.read_csv(
    "../../data/processed/"
    "production_rainfall_merged_2021_2025.csv"
)

In [47]:
test_merge.shape

(1403, 25)

In [48]:
test_merge.head()

,State,District,Crop,Year,Area,Production,Yield,Years_ Available,Complete_4_year_history,Previous_Yield,...,History_avg_yield,Yield_Deviation_Pct,Crop_Year_Rainfall_mm,Rainy_Days,Heavy_Rain_Days,Days_Available,Monsoon_Rainfall_mm,Rabi_Rainfall_mm,Historical_Avg_Rainfall,Rainfall_Deviation_Pct
0,Haryana,Ambala,Maize,2021-22,0.00,0.01,3945.0,4,True,NaN,...,NaN,NaN,1297.57,97,0,365,981.67,246.72,NaN,NaN
1,Haryana,Ambala,Maize,2022-23,0.00,0.00,3455.0,4,True,3945.0,...,3945.0,-12.420786,1567.66,110,1,365,1207.36,181.25,1297.570000,20.815062
2,Haryana,Ambala,Maize,2023-24,0.00,0.01,4642.0,4,True,3455.0,...,3700.0,25.459459,1301.31,84,3,366,1120.44,152.26,1432.615000,-9.165407
3,Haryana,Ambala,Maize,2024-25,0.00,0.00,3714.0,4,True,4642.0,...,4014.0,-7.473842,1447.69,111,1,365,1191.42,133.39,1388.846667,4.236849
4,Haryana,Ambala,Rice,2021-22,0.94,3.86,4107.0,4,True,NaN,...,NaN,NaN,1297.57,97,0,365,981.67,246.72,NaN,NaN