# Automated District Rainfall Collection

### This notebook obtains representative coordinates for each project district, downloads NASA POWER daily precipitation data, aggregates it into yearly  rainfall totals, and prepares a district-level rainfall dataset.

In [1]:
import pandas as pd
import numpy as np
import requests
import time

rainfall_daily_all = pd.read_csv(
    "../../data/processed/rainfall_daily_2021_2024.csv"
)

rainfall_daily_all["Date"] = pd.to_datetime(
    rainfall_daily_all["Date"]
)

In [2]:
production_history = pd.read_csv("../../data/processed/production_history_2021_2025.csv")

In [3]:
production_history.head()

,State,District,Crop,Year,Area,Production,Yield,Year_Order,Years_ Available,Complete_4_year_history,Previous_Yield,Previous_yield_percentage,Previous_area,Previous_Area_Percentage,Previous_Production,Production_Change_Pct,History_avg_yield,Yield_Deviation_Pct
0,Haryana,Ambala,Maize,2021-22,0.00,0.01,3945.0,2021,4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Haryana,Ambala,Maize,2022-23,0.00,0.00,3455.0,2022,4,True,3945.0,-12.420786,0.0,NaN,0.01,-100.0,3945.0,-12.420786
2,Haryana,Ambala,Maize,2023-24,0.00,0.01,4642.0,2023,4,True,3455.0,34.356006,0.0,NaN,0.00,NaN,3700.0,25.459459
3,Haryana,Ambala,Maize,2024-25,0.00,0.00,3714.0,2024,4,True,4642.0,-19.991383,0.0,NaN,0.01,-100.0,4014.0,-7.473842
4,Haryana,Ambala,Rice,2021-22,0.94,3.86,4107.0,2021,4,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Creating a unique district list 

districts = (
    production_history[
    ["State" , "District"]
    ].drop_duplicates().sort_values(["State" , "District"]).reset_index(drop=True))

In [5]:
districts.head()

     State       District
0  Haryana         Ambala
1  Haryana        Bhiwani
2  Haryana  Charkhi Dadri
3  Haryana      Faridabad
4  Haryana      Fatehabad

In [6]:
districts.shape

(120, 2)

In [7]:
# Checking the district count

districts.groupby("State")["District"].nunique()

State
Haryana          22
Punjab           23
Uttar Pradesh    75
Name: District, dtype: int64

### Need latitude and longitude for NASA Power

In [8]:
pip install geopy

Requirement already satisfied: geopy in e:\anaconda3\lib\site-packages (2.5.0)
Requirement already satisfied: geographiclib<3,>=1.52 in e:\anaconda3\lib\site-packages (from geopy) (2.1)
Note: you may need to restart the kernel to use updated packages.

In [9]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [10]:
# Creating the geocoder

geolocator = Nominatim(
    user_agent="crop-yield-risk-dashboard-data-analytics"
)

In [11]:
geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1)

In [12]:
# Testing the geocode for one district first 

location = geocode("Meerut district, Uttar Pradesh, India")

location

Location(Meerut, Uttar Pradesh, India, (29.0018557, 77.7679671, 0.0))

In [13]:
location.latitude

29.0018557

In [14]:
location.longitude

77.7679671

In [15]:
# Creating a geocoding function

def get_coordinates(row):
    
    query = (
        f"{row['District']} district, "
        f"{row['State']}, India"
    )

    try:
        location = geocode(query)

        if location:
            return pd.Series(
                [
                    location.latitude,
                    location.longitude,
                    location.address
                ]
            )

    except Exception as e:
        print(
            "Error:",
            row["District"],
            row["State"],
            e
        )

    return pd.Series(
        [np.nan, np.nan, None]
    )

In [16]:
# Geocoding all districts

districts[
    [
        "Latitude",
        "Longitude",
        "Geocoded_Address"
    ]
] = districts.apply(
    get_coordinates,
    axis=1
)

In [17]:
districts.isnull().sum()

State               0
District            0
Latitude            2
Longitude           2
Geocoded_Address    2
dtype: int64

In [18]:
failed_geocoding = districts[districts["Latitude"].isnull() | districts["Longitude"].isnull()]

failed_geocoding

,State,District,Latitude,Longitude,Geocoded_Address
42,Punjab,Shahid Bhagat Singh Nagar,NaN,NaN,NaN
113,Uttar Pradesh,Shrawasti,NaN,NaN,NaN

In [19]:
# Validate returned location 

districts[
["State" , "District" , "Geocoded_Address"]].head(20)

      State       District                                   Geocoded_Address
0   Haryana         Ambala                             Ambala, Haryana, India
1   Haryana        Bhiwani                            Bhiwani, Haryana, India
2   Haryana  Charkhi Dadri                      Charkhi Dadri, Haryana, India
3   Haryana      Faridabad                          Faridabad, Haryana, India
4   Haryana      Fatehabad                          Fatehabad, Haryana, India
5   Haryana       Gurugram  District And Sessions Court Gurugram, Sohna Ro...
6   Haryana          Hisar                              Hisar, Haryana, India
7   Haryana        Jhajjar                            Jhajjar, Haryana, India
8   Haryana           Jind                               Jind, Haryana, India
9   Haryana        Kaithal                            Kaithal, Haryana, India
10  Haryana         Karnal                             Karnal, Haryana, India
11  Haryana    Kurukshetra                        Kurukshetra, Haryana, India
12  Haryana   Mahendragarh                       Mahendragarh, Haryana, India
13  Haryana            Nuh                                Nuh, Haryana, India
14  Haryana         Palwal                             Palwal, Haryana, India
15  Haryana      Panchkula                          Panchkula, Haryana, India
16  Haryana        Panipat                            Panipat, Haryana, India
17  Haryana         Rewari                             Rewari, Haryana, India
18  Haryana         Rohtak                             Rohtak, Haryana, India
19  Haryana          Sirsa                              Sirsa, Haryana, India

In [20]:
# Saving the coordinates

districts.to_csv(
    "../../data/processed/district_coordinates.csv",
    index=False
)

In [21]:
# Testing NASA API for district Meerut

NASA_URL = (
    "https://power.larc.nasa.gov/"
    "api/temporal/daily/point"
)

In [22]:
meerut = districts[
    (districts["State"] == "Uttar Pradesh")
    & (districts["District"] == "Meerut")
].iloc[0]

In [23]:
params = {
    "parameters": "PRECTOTCORR",
    "community": "AG",
    "longitude": meerut["Longitude"],
    "latitude": meerut["Latitude"],
    "start": "20210101",
    "end": "20241231",
    "format": "JSON"
}

In [24]:
response = requests.get(
    NASA_URL,
    params=params,
    timeout=60
)

In [25]:
response.status_code

200

In [26]:
# Inspecting NASA json 

data = response.json()

data.keys()

dict_keys(['type', 'geometry', 'properties', 'header', 'messages', 'parameters', 'times'])

In [27]:
data["properties"]["parameter"]["PRECTOTCORR"]

{'20210101': 0.0,
 '20210102': 5.02,
 '20210103': 15.6,
 '20210104': 0.22,
 '20210105': 6.13,
 '20210106': 7.16,
 '20210107': 0.1,
 '20210108': 0.21,
 '20210109': 0.71,
 '20210110': 0.0,
 '20210111': 0.0,
 '20210112': 0.0,
 '20210113': 0.0,
 '20210114': 0.0,
 '20210115': 0.0,
 '20210116': 0.0,
 '20210117': 0.0,
 '20210118': 0.0,
 '20210119': 0.0,
 '20210120': 0.0,
 '20210121': 0.0,
 '20210122': 0.0,
 '20210123': 0.0,
 '20210124': 0.0,
 '20210125': 0.0,
 '20210126': 0.0,
 '20210127': 0.0,
 '20210128': 0.0,
 '20210129': 0.0,
 '20210130': 0.0,
 '20210131': 0.0,
 '20210201': 0.0,
 '20210202': 0.0,
 '20210203': 0.18,
 '20210204': 4.95,
 '20210205': 0.23,
 '20210206': 0.0,
 '20210207': 0.0,
 '20210208': 0.0,
 '20210209': 0.0,
 '20210210': 0.0,
 '20210211': 0.0,
 '20210212': 0.0,
 '20210213': 0.0,
 '20210214': 0.0,
 '20210215': 0.0,
 '20210216': 0.0,
 '20210217': 0.0,
 '20210218': 0.0,
 '20210219': 0.0,
 '20210220': 0.0,
 '20210221': 0.0,
 '20210222': 0.0,
 '20210223': 0.0,
 '20210224': 0.0,
 '20210225': 0.0,
 '20210226': 0.0,
 '20210227': 1.5,
 '20210228': 0.0,
 '20210301': 0.0,
 '20210302': 0.0,
 '20210303': 0.0,
 '20210304': 0.0,
 '20210305': 0.0,
 '20210306': 0.0,
 '20210307': 0.0,
 '20210308': 0.33,
 '20210309': 0.0,
 '20210310': 0.14,
 '20210311': 0.0,
 '20210312': 0.68,
 '20210313': 0.01,
 '20210314': 0.0,
 '20210315': 0.0,
 '20210316': 0.0,
 '20210317': 0.0,
 '20210318': 0.0,
 '20210319': 0.0,
 '20210320': 0.0,
 '20210321': 0.0,
 '20210322': 0.05,
 '20210323': 0.05,
 '20210324': 0.08,
 '20210325': 0.0,
 '20210326': 0.0,
 '20210327': 0.0,
 '20210328': 0.0,
 '20210329': 0.0,
 '20210330': 0.0,
 '20210331': 0.0,
 '20210401': 0.0,
 '20210402': 0.0,
 '20210403': 0.0,
 '20210404': 0.0,
 '20210405': 0.0,
 '20210406': 0.0,
 '20210407': 0.09,
 '20210408': 0.0,
 '20210409': 0.0,
 '20210410': 0.0,
 '20210411': 0.0,
 '20210412': 0.0,
 '20210413': 0.0,
 '20210414': 0.0,
 '20210415': 0.0,
 '20210416': 0.53,
 '20210417': 0.51,
 '20210418': 0.0,
 '20210419': 0.19,
 '20210420': 0.2,
 '20210421': 2.83,
 '20210422': 0.51,
 '20210423': 0.7,
 '20210424': 0.0,
 '20210425': 0.0,
 '20210426': 0.0,
 '20210427': 0.0,
 '20210428': 0.0,
 '20210429': 0.0,
 '20210430': 0.36,
 '20210501': 0.25,
 '20210502': 0.42,
 '20210503': 0.0,
 '20210504': 0.01,
 '20210505': 0.01,
 '20210506': 4.61,
 '20210507': 3.06,
 '20210508': 0.0,
 '20210509': 0.36,
 '20210510': 1.53,
 '20210511': 0.02,
 '20210512': 0.23,
 '20210513': 2.45,
 '20210514': 0.0,
 '20210515': 0.06,
 '20210516': 0.14,
 '20210517': 0.0,
 '20210518': 1.09,
 '20210519': 42.25,
 '20210520': 46.49,
 '20210521': 2.95,
 '20210522': 3.34,
 '20210523': 0.0,
 '20210524': 0.0,
 '20210525': 0.0,
 '20210526': 0.0,
 '20210527': 0.0,
 '20210528': 0.0,
 '20210529': 1.73,
 '20210530': 1.95,
 '20210531': 0.0,
 '20210601': 17.09,
 '20210602': 0.0,
 '20210603': 0.1,
 '20210604': 0.68,
 '20210605': 1.37,
 '20210606': 0.03,
 '20210607': 0.0,
 '20210608': 0.03,
 '20210609': 0.0,
 '20210610': 4.19,
 '20210611': 2.49,
 '20210612': 7.51,
 '20210613': 1.96,
 '20210614': 0.08,
 '20210615': 0.01,
 '20210616': 5.75,
 '20210617': 30.19,
 '20210618': 7.45,
 '20210619': 9.71,
 '20210620': 3.15,
 '20210621': 0.12,
 '20210622': 0.0,
 '20210623': 0.0,
 '20210624': 0.0,
 '20210625': 5.03,
 '20210626': 1.55,
 '20210627': 0.02,
 '20210628': 0.0,
 '20210629': 0.0,
 '20210630': 0.0,
 '20210701': 0.0,
 '20210702': 1.41,
 '20210703': 3.74,
 '20210704': 0.66,
 '20210705': 0.04,
 '20210706': 0.0,
 '20210707': 0.01,
 '20210708': 0.19,
 '20210709': 8.94,
 '20210710': 0.06,
 '20210711': 0.71,
 '20210712': 2.21,
 '20210713': 17.87,
 '20210714': 23.09,
 '20210715': 15.62,
 '20210716': 1.0,
 '20210717': 3.46,
 '20210718': 31.58,
 '20210719': 57.38,
 '20210720': 29.88,
 '20210721': 7.43,
 '20210722': 8.95,
 '20210723': 7.58,
 '20210724': 0.59,
 '20210725': 0.19,
 '20210726': 4.52,
 '20210727': 25.94,
 '20210728': 41.53,
 '20210729': 17.17,
 '20210730': 19.76,
 '20210731': 10.7,
 '20210801': 7.8,
 '20210802': 1.71,
 '20210803': 1.68,
 '20210804': 0.36,
 '20210805': 0.53,
 '20210806': 0.14,
 '20210807': 16.73,
 '20210808': 5.65,
 '20210809': 10.04,
 '20210810': 0.3,
 '20210811': 0.0,
 '20210812': 0.28,
 '20210813': 3.18,
 '20210814': 0.41,
 '20210815': 0.14,
 '20210816': 0.17,
 '20210817': 0.0,
 '20210818': 0.06,
 '20210819': 5.87,
 '20210820': 63.77,
 '20210821': 20.16,
 '20210822': 1.1,
 '20210823': 0.51,
 '20210824': 1.56,
 '20210825': 1.75,
 '20210826': 0.32,
 '20210827': 12.64,
 '20210828': 11.38,
 '20210829': 1.8,
 '20210830': 1.24,
 '20210831': 3.56,
 '20210901': 33.28,
 '20210902': 16.19,
 '20210903': 17.3,
 '20210904': 9.33,
 '20210905': 1.0,
 '20210906': 6.37,
 '20210907': 5.49,
 '20210908': 0.15,
 '20210909': 7.33,
 '20210910': 19.45,
 '20210911': 15.51,
 '20210912': 11.72,
 '20210913': 13.29,
 '20210914': 0.47,
 '20210915': 0.22,
 '20210916': 9.34,
 '20210917': 0.82,
 '20210918': 0.0,
 '20210919': 0.27,
 '20210920': 0.2,
 '20210921': 9.9,
 '20210922': 16.86,
 '20210923': 11.39,
 '20210924': 5.9,
 '20210925': 2.94,
 '20210926': 0.52,
 '20210927': 0.0,
 '20210928': 0.13,
 '20210929': 0.45,
 '20210930': 5.85,
 '20211001': 12.52,
 '20211002': 0.14,
 '20211003': 0.02,
 '20211004': 0.72,
 '20211005': 4.88,
 '20211006': 0.02,
 '20211007': 0.0,
 '20211008': 0.0,
 '20211009': 0.0,
 '20211010': 0.0,
 '20211011': 0.0,
 '20211012': 0.0,
 '20211013': 0.0,
 '20211014': 0.0,
 '20211015': 0.0,
 '20211016': 0.0,
 '20211017': 16.91,
 '20211018': 71.69,
 '20211019': 0.02,
 '20211020': 0.36,
 '20211021': 0.0,
 '20211022': 0.0,
 '20211023': 0.0,
 '20211024': 13.04,
 '20211025': 1.03,
 '20211026': 0.0,
 '20211027': 0.0,
 '20211028': 0.0,
 '20211029': 0.0,
 '20211030': 0.0,
 '20211031': 0.0,
 '20211101': 0.0,
 '20211102': 0.0,
 '20211103': 0.0,
 '20211104': 0.0,
 '20211105': 0.0,
 '20211106': 0.0,
 '20211107': 0.0,
 '20211108': 0.0,
 '20211109': 0.0,
 '20211110': 0.0,
 '20211111': 0.0,
 '20211112': 0.0,
 '20211113': 0.0,
 '20211114': 0.0,
 '20211115': 0.0,
 '20211116': 0.0,
 '20211117': 0.0,
 '20211118': 0.0,
 '20211119': 0.0,
 '20211120': 0.0,
 '20211121': 0.0,
 '20211122': 0.0,
 '20211123': 0.0,
 '20211124': 0.0,
 '20211125': 0.0,
 '20211126': 0.0,
 '20211127': 0.0,
 '20211128': 0.0,
 '20211129': 0.0,
 '20211130': 0.0,
 '20211201': 0.0,
 '20211202': 0.0,
 '20211203': 0.95,
 '20211204': 0.0,
 '20211205': 0.02,
 '20211206': 0.45,
 '20211207': 0.0,
 '20211208': 0.0,
 '20211209': 0.0,
 '20211210': 0.0,
 '20211211': 0.0,
 '20211212': 0.0,
 '20211213': 0.0,
 '20211214': 0.0,
 '20211215': 0.0,
 '20211216': 0.0,
 '20211217': 0.0,
 '20211218': 0.0,
 '20211219': 0.0,
 '20211220': 0.0,
 '20211221': 0.0,
 '20211222': 0.0,
 '20211223': 0.0,
 '20211224': 0.0,
 '20211225': 0.0,
 '20211226': 0.15,
 '20211227': 0.91,
 '20211228': 0.07,
 '20211229': 0.86,
 '20211230': 0.0,
 '20211231': 0.0,
 '20220101': 0.0,
 '20220102': 0.0,
 '20220103': 0.0,
 '20220104': 0.0,
 '20220105': 9.69,
 '20220106': 0.86,
 '20220107': 1.35,
 '20220108': 32.4,
 '20220109': 17.71,
 '20220110': 3.45,
 '20220111': 0.36,
 '20220112': 0.05,
 '20220113': 0.0,
 '20220114': 0.0,
 '20220115': 0.0,
 '20220116': 0.0,
 '20220117': 0.0,
 '20220118': 0.0,
 '20220119': 0.0,
 '20220120': 0.89,
 '20220121': 0.12,
 '20220122': 6.77,
 '20220123': 16.48,
 '20220124': 0.17,
 '20220125': 0.14,
 '20220126': 0.09,
 '20220127': 0.01,
 '20220128': 0.0,
 '20220129': 0.0,
 '20220130': 0.0,
 '20220131': 0.0,
 '20220201': 0.0,
 '20220202': 0.0,
 '20220203': 14.44,
 '20220204': 0.89,
 '20220205': 0.01,
 '20220206': 0.0,
 '20220207': 0.0,
 '20220208': 0.94,
 '20220209': 8.7,
 '20220210': 0.0,
 '20220211': 0.0,
 '20220212': 0.0,
 '20220213': 0.0,
 '20220214': 0.0,
 '20220215': 0.0,
 '20220216': 0.0,
 '20220217': 0.0,
 '20220218': 0.0,
 '20220219': 0.02,
 '20220220': 0.0,
 '20220221': 0.0,
 '20220222': 0.0,
 '20220223': 0.06,
 '20220224': 0.11,
 '20220225': 1.27,
 '20220226': 5.09,
 '20220227': 0.08,
 '20220228': 0.0,
 '20220301': 0.0,
 '20220302': 0.0,
 '20220303': 0.0,
 '20220304': 0.0,
 '20220305': 0.0,
 '20220306': 0.0,
 '20220307': 0.0,
 '20220308': 0.0,
 '20220309': 0.0,
 '20220310': 0.0,
 '20220311': 0.0,
 '20220312': 0.0,
 '20220313': 0.0,
 '20220314': 0.0,
 '20220315': 0.0,
 '20220316': 0.0,
 '20220317': 0.0,
 '20220318': 0.0,
 '20220319': 0.0,
 '20220320': 0.0,
 '20220321': 0.0,
 '20220322': 0.0,
 '20220323': 0.0,
 '20220324': 0.0,
 '20220325': 0.0,
 '20220326': 0.0,
 '20220327': 0.0,
 '20220328': 0.0,
 '20220329': 0.0,
 '20220330': 0.0,
 '20220331': 0.0,
 '20220401': 0.0,
 '20220402': 0.0,
 '20220403': 0.0,
 '20220404': 0.0,
 '20220405': 0.0,
 '20220406': 0.0,
 '20220407': 0.0,
 '20220408': 0.0,
 '20220409': 0.0,
 '20220410': 0.0,
 '20220411': 0.0,
 '20220412': 0.0,
 '20220413': 0.0,
 '20220414': 0.06,
 '20220415': 0.03,
 '20220416': 0.0,
 '20220417': 0.0,
 '20220418': 0.0,
 '20220419': 0.0,
 '20220420': 0.0,
 '20220421': 0.04,
 '20220422': 0.0,
 '20220423': 0.0,
 '20220424': 0.0,
 '20220425': 0.0,
 '20220426': 0.0,
 '20220427': 0.0,
 '20220428': 0.0,
 '20220429': 0.0,
 '20220430': 0.0,
 '20220501': 0.0,
 '20220502': 0.0,
 '20220503': 0.0,
 '20220504': 6.29,
 '20220505': 0.77,
 '20220506': 0.0,
 '20220507': 0.0,
 '20220508': 0.03,
 '20220509': 0.02,
 '20220510': 0.08,
 '20220511': 0.18,
 '20220512': 0.03,
 '20220513': 0.1,
 '20220514': 0.0,
 '20220515': 0.0,
 '20220516': 0.0,
 '20220517': 0.08,
 '20220518': 0.0,
 '20220519': 0.11,
 '20220520': 0.0,
 '20220521': 0.84,
 '20220522': 0.0,
 '20220523': 26.14,
 '20220524': 9.15,
 '20220525': 0.18,
 '20220526': 0.0,
 '20220527': 0.05,
 '20220528': 0.59,
 '20220529': 0.97,
 '20220530': 0.88,
 '20220531': 0.81,
 '20220601': 0.02,
 '20220602': 0.0,
 '20220603': 0.0,
 '20220604': 0.0,
 '20220605': 0.0,
 '20220606': 0.0,
 '20220607': 0.0,
 '20220608': 0.0,
 '20220609': 0.0,
 '20220610': 0.0,
 '20220611': 0.05,
 '20220612': 0.03,
 '20220613': 0.0,
 '20220614': 0.0,
 '20220615': 0.22,
 '20220616': 0.61,
 '20220617': 18.36,
 '20220618': 8.12,
 '20220619': 1.27,
 '20220620': 0.19,
 '20220621': 1.09,
 '20220622': 0.08,
 '20220623': 0.0,
 '20220624': 0.0,
 '20220625': 0.0,
 '20220626': 0.21,
 '20220627': 0.0,
 '20220628': 0.77,
 '20220629': 6.92,
 '20220630': 35.73,
 '20220701': 3.79,
 '20220702': 5.63,
 '20220703': 0.91,
 '20220704': 2.82,
 '20220705': 1.23,
 '20220706': 2.34,
 '20220707': 0.04,
 '20220708': 0.07,
 '20220709': 7.54,
 '20220710': 1.06,
 '20220711': 6.36,
 '20220712': 28.35,
 '20220713': 0.38,
 '20220714': 1.28,
 '20220715': 0.26,
 '20220716': 10.69,
 '20220717': 1.45,
 '20220718': 0.56,
 '20220719': 3.05,
 '20220720': 15.02,
 '20220721': 11.8,
 '20220722': 1.71,
 '20220723': 5.15,
 '20220724': 1.43,
 '20220725': 0.54,
 '20220726': 2.36,
 '20220727': 5.58,
 '20220728': 14.44,
 '20220729': 11.12,
 '20220730': 20.26,
 '20220731': 11.66,
 '20220801': 4.18,
 '20220802': 0.7,
 '20220803': 1.77,
 '20220804': 7.32,
 '20220805': 5.55,
 '20220806': 0.85,
 '20220807': 2.84,
 '20220808': 1.15,
 '20220809': 0.63,
 '20220810': 0.04,
 '20220811': 1.99,
 '20220812': 0.01,
 '20220813': 0.0,
 '20220814': 1.44,
 '20220815': 10.0,
 '20220816': 0.53,
 '20220817': 0.1,
 '20220818': 0.0,
 '20220819': 3.22,
 '20220820': 3.7,
 '20220821': 0.12,
 '20220822': 0.37,
 '20220823': 1.07,
 '20220824': 2.63,
 '20220825': 0.14,
 '20220826': 0.0,
 '20220827': 0.0,
 '20220828': 0.78,
 '20220829': 1.32,
 '20220830': 2.83,
 '20220831': 0.06,
 '20220901': 0.89,
 '20220902': 1.97,
 '20220903': 0.01,
 '20220904': 0.0,
 '20220905': 0.49,
 '20220906': 0.0,
 '20220907': 0.16,
 '20220908': 0.1,
 '20220909': 0.18,
 '20220910': 1.62,
 '20220911': 1.07,
 '20220912': 0.95,
 '20220913': 1.41,
 '20220914': 2.16,
 '20220915': 16.26,
 '20220916': 22.05,
 '20220917': 3.5,
 '20220918': 2.41,
 '20220919': 3.88,
 '20220920': 13.7,
 '20220921': 16.0,
 '20220922': 47.05,
 '20220923': 30.05,
 '20220924': 46.2,
 '20220925': 20.5,
 '20220926': 0.44,
 '20220927': 0.0,
 '20220928': 0.33,
 '20220929': 0.0,
 '20220930': 0.0,
 '20221001': 0.03,
 '20221002': 0.02,
 '20221003': 0.0,
 '20221004': 0.0,
 '20221005': 0.56,
 '20221006': 2.26,
 '20221007': 6.11,
 '20221008': 12.86,
 '20221009': 93.95,
 '20221010': 15.75,
 '20221011': 10.11,
 '20221012': 4.77,
 '20221013': 0.0,
 '20221014': 0.0,
 '20221015': 0.0,
 '20221016': 0.0,
 '20221017': 0.0,
 '20221018': 0.01,
 '20221019': 0.0,
 '20221020': 0.0,
 '20221021': 0.0,
 '20221022': 0.0,
 '20221023': 0.0,
 '20221024': 0.0,
 '20221025': 0.0,
 '20221026': 0.0,
 '20221027': 0.0,
 '20221028': 0.0,
 '20221029': 0.0,
 '20221030': 0.0,
 '20221031': 0.0,
 '20221101': 0.0,
 '20221102': 0.0,
 '20221103': 0.0,
 '20221104': 0.0,
 '20221105': 0.0,
 '20221106': 0.0,
 '20221107': 0.0,
 '20221108': 0.0,
 '20221109': 0.0,
 '20221110': 0.01,
 '20221111': 0.03,
 '20221112': 0.0,
 '20221113': 0.0,
 '20221114': 0.0,
 '20221115': 0.04,
 '20221116': 0.0,
 '20221117': 0.0,
 '20221118': 0.0,
 '20221119': 0.0,
 '20221120': 0.0,
 '20221121': 0.0,
 '20221122': 0.0,
 '20221123': 0.0,
 '20221124': 0.0,
 '20221125': 0.0,
 '20221126': 0.0,
 '20221127': 0.0,
 '20221128': 0.0,
 '20221129': 0.0,
 '20221130': 0.0,
 '20221201': 0.0,
 '20221202': 0.0,
 '20221203': 0.0,
 '20221204': 0.0,
 '20221205': 0.0,
 '20221206': 0.0,
 '20221207': 0.0,
 '20221208': 0.0,
 '20221209': 0.0,
 '20221210': 0.0,
 '20221211': 0.0,
 '20221212': 0.0,
 '20221213': 0.0,
 '20221214': 0.0,
 '20221215': 0.0,
 '20221216': 0.0,
 '20221217': 0.0,
 '20221218': 0.0,
 '20221219': 0.0,
 '20221220': 0.0,
 '20221221': 0.0,
 '20221222': 0.0,
 '20221223': 0.0,
 '20221224': 0.0,
 '20221225': 0.0,
 '20221226': 0.0,
 '20221227': 0.0,
 '20221228': 0.0,
 '20221229': 0.02,
 '20221230': 0.02,
 '20221231': 0.0,
 '20230101': 0.0,
 '20230102': 0.0,
 '20230103': 0.0,
 '20230104': 0.0,
 '20230105': 0.0,
 '20230106': 0.0,
 '20230107': 0.0,
 '20230108': 0.0,
 '20230109': 0.0,
 '20230110': 0.0,
 '20230111': 0.21,
 '20230112': 6.77,
 '20230113': 0.35,
 '20230114': 0.17,
 '20230115': 0.0,
 '20230116': 0.0,
 '20230117': 0.0,
 '20230118': 0.0,
 '20230119': 0.24,
 '20230120': 0.37,
 '20230121': 0.0,
 '20230122': 0.0,
 '20230123': 0.17,
 '20230124': 3.89,
 '20230125': 0.19,
 '20230126': 0.0,
 '20230127': 0.0,
 '20230128': 0.0,
 '20230129': 0.01,
 '20230130': 11.95,
 '20230131': 0.0,
 '20230201': 0.0,
 '20230202': 0.0,
 '20230203': 0.0,
 '20230204': 0.0,
 '20230205': 0.0,
 '20230206': 0.0,
 '20230207': 0.01,
 '20230208': 0.0,
 '20230209': 0.0,
 '20230210': 0.0,
 '20230211': 0.01,
 '20230212': 0.03,
 '20230213': 0.0,
 '20230214': 0.0,
 '20230215': 0.0,
 '20230216': 0.0,
 '20230217': 0.0,
 '20230218': 0.0,
 '20230219': 0.0,
 '20230220': 0.0,
 '20230221': 0.0,
 '20230222': 0.22,
 '20230223': 0.0,
 '20230224': 0.0,
 '20230225': 0.0,
 '20230226': 0.0,
 '20230227': 0.0,
 '20230228': 0.0,
 '20230301': 0.0,
 '20230302': 0.0,
 '20230303': 0.0,
 '20230304': 0.0,
 '20230305': 0.0,
 '20230306': 0.0,
 '20230307': 0.0,
 '20230308': 0.0,
 '20230309': 0.67,
 '20230310': 0.0,
 '20230311': 0.0,
 '20230312': 0.0,
 '20230313': 0.0,
 '20230314': 0.04,
 '20230315': 0.0,
 '20230316': 0.01,
 '20230317': 0.27,
 '20230318': 7.55,
 '20230319': 1.17,
 '20230320': 20.2,
 '20230321': 20.68,
 '20230322': 0.01,
 '20230323': 0.0,
 '20230324': 2.54,
 '20230325': 6.33,
 '20230326': 0.02,
 '20230327': 0.0,
 '20230328': 0.0,
 '20230329': 0.0,
 '20230330': 6.01,
 '20230331': 10.72,
 '20230401': 2.44,
 '20230402': 0.0,
 '20230403': 2.54,
 '20230404': 0.0,
 '20230405': 0.0,
 '20230406': 0.0,
 '20230407': 0.0,
 '20230408': 0.0,
 '20230409': 0.0,
 '20230410': 0.0,
 '20230411': 0.0,
 '20230412': 0.0,
 '20230413': 0.0,
 '20230414': 0.0,
 '20230415': 0.0,
 '20230416': 0.0,
 '20230417': 0.0,
 '20230418': 0.0,
 '20230419': 0.01,
 '20230420': 1.8,
 '20230421': 0.75,
 '20230422': 0.11,
 '20230423': 0.06,
 '20230424': 0.03,
 '20230425': 0.01,
 '20230426': 0.0,
 '20230427': 0.72,
 '20230428': 0.67,
 '20230429': 1.26,
 '20230430': 2.31,
 '20230501': 18.24,
 '20230502': 4.41,
 '20230503': 10.5,
 '20230504': 3.78,
 '20230505': 0.0,
 '20230506': 0.01,
 '20230507': 0.01,
 '20230508': 0.64,
 '20230509': 0.02,
 '20230510': 0.0,
 '20230511': 0.0,
 '20230512': 0.0,
 '20230513': 0.0,
 '20230514': 0.0,
 '20230515': 0.0,
 '20230516': 0.01,
 '20230517': 0.0,
 '20230518': 6.48,
 '20230519': 0.0,
 '20230520': 0.0,
 '20230521': 0.0,
 '20230522': 0.0,
 '20230523': 1.35,
 '20230524': 1.35,
 '20230525': 6.37,
 '20230526': 10.02,
 '20230527': 2.51,
 '20230528': 0.29,
 '20230529': 1.13,
 '20230530': 0.98,
 '20230531': 3.75,
 '20230601': 0.07,
 '20230602': 0.06,
 '20230603': 0.0,
 '20230604': 0.32,
 '20230605': 0.1,
 '20230606': 0.02,
 '20230607': 0.01,
 '20230608': 0.0,
 '20230609': 0.0,
 '20230610': 0.23,
 '20230611': 0.0,
 '20230612': 0.0,
 '20230613': 0.0,
 '20230614': 0.0,
 '20230615': 0.0,
 '20230616': 0.59,
 '20230617': 0.96,
 '20230618': 0.99,
 '20230619': 1.81,
 '20230620': 6.06,
 '20230621': 2.64,
 '20230622': 9.66,
 '20230623': 1.84,
 '20230624': 31.23,
 '20230625': 30.79,
 '20230626': 8.9,
 '20230627': 7.23,
 '20230628': 12.39,
 '20230629': 11.61,
 '20230630': 9.81,
 '20230701': 2.21,
 '20230702': 0.05,
 '20230703': 0.14,
 '20230704': 1.32,
 '20230705': 18.71,
 '20230706': 21.03,
 '20230707': 14.11,
 '20230708': 27.24,
 '20230709': 52.16,
 '20230710': 28.93,
 '20230711': 14.46,
 '20230712': 36.52,
 '20230713': 8.72,
 '20230714': 7.2,
 '20230715': 3.38,
 '20230716': 2.74,
 '20230717': 5.26,
 '20230718': 21.57,
 '20230719': 0.88,
 '20230720': 0.13,
 '20230721': 2.76,
 '20230722': 4.34,
 '20230723': 0.51,
 '20230724': 0.36,
 '20230725': 18.56,
 '20230726': 16.23,
 '20230727': 13.67,
 '20230728': 19.06,
 '20230729': 4.76,
 '20230730': 1.73,
 '20230731': 1.79,
 '20230801': 0.04,
 '20230802': 0.59,
 '20230803': 5.08,
 '20230804': 45.25,
 '20230805': 28.95,
 '20230806': 11.36,
 '20230807': 2.33,
 '20230808': 0.69,
 '20230809': 5.66,
 '20230810': 11.07,
 '20230811': 4.43,
 '20230812': 0.18,
 '20230813': 1.12,
 '20230814': 1.98,
 '20230815': 2.08,
 '20230816': 2.54,
 '20230817': 1.45,
 '20230818': 0.65,
 '20230819': 7.38,
 '20230820': 1.19,
 '20230821': 2.2,
 '20230822': 12.96,
 '20230823': 28.49,
 '20230824': 0.76,
 '20230825': 0.11,
 '20230826': 0.67,
 '20230827': 0.13,
 '20230828': 0.13,
 '20230829': 0.02,
 '20230830': 0.04,
 '20230831': 0.0,
 '20230901': 0.0,
 '20230902': 0.0,
 '20230903': 0.0,
 '20230904': 0.0,
 '20230905': 0.2,
 '20230906': 0.04,
 '20230907': 0.56,
 '20230908': 9.63,
 '20230909': 11.05,
 '20230910': 69.48,
 '20230911': 0.37,
 '20230912': 0.28,
 '20230913': 0.31,
 '20230914': 14.14,
 '20230915': 3.94,
 '20230916': 9.68,
 '20230917': 3.04,
 '20230918': 0.11,
 '20230919': 0.03,
 '20230920': 0.0,
 '20230921': 0.04,
 '20230922': 1.83,
 '20230923': 7.6,
 '20230924': 2.36,
 '20230925': 0.0,
 '20230926': 0.0,
 '20230927': 0.0,
 ...}

In [28]:
# Converting one NASA reponse into dataframe 

rainfall_dict = (  data["properties"]["parameter"]["PRECTOTCORR"]
)

In [29]:
test_rainfall = pd.DataFrame(rainfall_dict.items(),columns=["Date", "Rainfall_mm"])

In [30]:
test_rainfall.head()

       Date  Rainfall_mm
0  20210101         0.00
1  20210102         5.02
2  20210103        15.60
3  20210104         0.22
4  20210105         6.13

In [31]:
# Converting the date

test_rainfall["Date"] = pd.to_datetime(
    test_rainfall["Date"],
    format="%Y%m%d"
)

In [32]:
test_rainfall.head()

        Date  Rainfall_mm
0 2021-01-01         0.00
1 2021-01-02         5.02
2 2021-01-03        15.60
3 2021-01-04         0.22
4 2021-01-05         6.13

In [33]:
test_rainfall["Year"] = (
    test_rainfall["Date"].dt.year
)

In [34]:
test_rainfall.head()

        Date  Rainfall_mm  Year
0 2021-01-01         0.00  2021
1 2021-01-02         5.02  2021
2 2021-01-03        15.60  2021
3 2021-01-04         0.22  2021
4 2021-01-05         6.13  2021

In [35]:
# Aggregating test result to annual rainfall 

test_annual = (
    test_rainfall
    .groupby(
        "Year",
        as_index=False
    )["Rainfall_mm"]
    .sum()
)

test_annual

   Year  Rainfall_mm
0  2021      1124.21
1  2022       857.40
2  2023      1007.27
3  2024       927.64

In [36]:
# Creating the NASA function 
def fetch_nasa_rainfall(
    state,
    district,
    latitude,
    longitude,
    start_date,
    end_date
):
    params = {
        "parameters": "PRECTOTCORR",
        "community": "AG",
        "longitude": longitude,
        "latitude": latitude,
        "start": start_date,
        "end": end_date,
        "format": "JSON"
    }

    try:
        response = requests.get(
            NASA_URL,
            params=params,
            timeout=60
        )

        response.raise_for_status()

        data = response.json()

        rainfall_dict = (
            data["properties"]
                ["parameter"]
                ["PRECTOTCORR"]
        )

        temp = pd.DataFrame(
            rainfall_dict.items(),
            columns=[
                "Date",
                "Rainfall_mm"
            ]
        )

        temp["Date"] = pd.to_datetime(
            temp["Date"],
            format="%Y%m%d"
        )

        temp["Year"] = temp["Date"].dt.year

        temp["State"] = state
        temp["District"] = district
        temp["Latitude"] = latitude
        temp["Longitude"] = longitude

        return temp

    except Exception as e:
        print(
            f"Failed: {district}, {state}: {e}"
        )

        return None

In [37]:
# Fetch Jan–Jun 2025 for every district

rainfall_2025_part = []

In [38]:
for _, row in districts.dropna(
    subset=[
        "Latitude",
        "Longitude"
    ]
).iterrows():

    print(
        "Fetching 2025:",
        row["District"],
        row["State"]
    )

    result = fetch_nasa_rainfall(
        row["State"],
        row["District"],
        row["Latitude"],
        row["Longitude"],
        "20250101",
        "20250630"
    )

    if result is not None:
        rainfall_2025_part.append(result)

    time.sleep(1)

Fetching 2025: Ambala Haryana
Fetching 2025: Bhiwani Haryana
Fetching 2025: Charkhi Dadri Haryana
Fetching 2025: Faridabad Haryana
Fetching 2025: Fatehabad Haryana
Fetching 2025: Gurugram Haryana
Fetching 2025: Hisar Haryana
Fetching 2025: Jhajjar Haryana
Fetching 2025: Jind Haryana
Fetching 2025: Kaithal Haryana
Fetching 2025: Karnal Haryana
Fetching 2025: Kurukshetra Haryana
Fetching 2025: Mahendragarh Haryana
Fetching 2025: Nuh Haryana
Fetching 2025: Palwal Haryana
Fetching 2025: Panchkula Haryana
Fetching 2025: Panipat Haryana
Fetching 2025: Rewari Haryana
Fetching 2025: Rohtak Haryana
Fetching 2025: Sirsa Haryana
Fetching 2025: Sonipat Haryana
Fetching 2025: Yamunanagar Haryana
Fetching 2025: Amritsar Punjab
Fetching 2025: Barnala Punjab
Fetching 2025: Bathinda Punjab
Fetching 2025: Faridkot Punjab
Fetching 2025: Fatehgarh Sahib Punjab
Fetching 2025: Fazilka Punjab
Fetching 2025: Ferozepur Punjab
Fetching 2025: Gurdaspur Punjab
Fetching 2025: Hoshiarpur Punjab
Fetching 2025: Jalandhar Punjab
Fetching 2025: Kapurthala Punjab
Fetching 2025: Ludhiana Punjab
Fetching 2025: Malerkotla Punjab
Fetching 2025: Mansa Punjab
Fetching 2025: Moga Punjab
Fetching 2025: Pathankot Punjab
Fetching 2025: Patiala Punjab
Fetching 2025: Rupnagar Punjab
Fetching 2025: S.A.S Nagar Punjab
Fetching 2025: Sangrur Punjab
Fetching 2025: Sri Muktsar Sahib Punjab
Fetching 2025: Tarn Taran Punjab
Fetching 2025: Agra Uttar Pradesh
Fetching 2025: Aligarh Uttar Pradesh
Fetching 2025: Ambedkar Nagar Uttar Pradesh
Fetching 2025: Amethi Uttar Pradesh
Fetching 2025: Amroha Uttar Pradesh
Fetching 2025: Auraiya Uttar Pradesh
Fetching 2025: Ayodhya Uttar Pradesh
Fetching 2025: Azamgarh Uttar Pradesh
Fetching 2025: Baghpat Uttar Pradesh
Fetching 2025: Bahraich Uttar Pradesh
Fetching 2025: Ballia Uttar Pradesh
Fetching 2025: Balrampur Uttar Pradesh
Fetching 2025: Banda Uttar Pradesh
Fetching 2025: Bara Banki Uttar Pradesh
Fetching 2025: Bareilly Uttar Pradesh
Fetching 2025: Basti Uttar Pradesh
Fetching 2025: Bhadohi Uttar Pradesh
Fetching 2025: Bijnor Uttar Pradesh
Fetching 2025: Budaun Uttar Pradesh
Fetching 2025: Bulandshahr Uttar Pradesh
Fetching 2025: Chandauli Uttar Pradesh
Fetching 2025: Chitrakoot Uttar Pradesh
Fetching 2025: Deoria Uttar Pradesh
Fetching 2025: Etah Uttar Pradesh
Fetching 2025: Etawah Uttar Pradesh
Fetching 2025: Farrukhabad Uttar Pradesh
Fetching 2025: Fatehpur Uttar Pradesh
Fetching 2025: Firozabad Uttar Pradesh
Fetching 2025: Gautam Buddha Nagar Uttar Pradesh
Fetching 2025: Ghaziabad Uttar Pradesh
Fetching 2025: Ghazipur Uttar Pradesh
Fetching 2025: Gonda Uttar Pradesh
Fetching 2025: Gorakhpur Uttar Pradesh
Fetching 2025: Hamirpur Uttar Pradesh
Fetching 2025: Hapur Uttar Pradesh
Fetching 2025: Hardoi Uttar Pradesh
Fetching 2025: Hathras Uttar Pradesh
Fetching 2025: Jalaun Uttar Pradesh
Fetching 2025: Jaunpur Uttar Pradesh
Fetching 2025: Jhansi Uttar Pradesh
Fetching 2025: Kannauj Uttar Pradesh
Fetching 2025: Kanpur Dehat Uttar Pradesh
Fetching 2025: Kanpur Nagar Uttar Pradesh
Fetching 2025: Kasganj Uttar Pradesh
Fetching 2025: Kaushambi Uttar Pradesh
Fetching 2025: Kheri Uttar Pradesh
Fetching 2025: Kushinagar Uttar Pradesh
Fetching 2025: Lalitpur Uttar Pradesh
Fetching 2025: Lucknow Uttar Pradesh
Fetching 2025: Mahoba Uttar Pradesh
Fetching 2025: Mahrajganj Uttar Pradesh
Fetching 2025: Mainpuri Uttar Pradesh
Fetching 2025: Mathura Uttar Pradesh
Fetching 2025: Mau Uttar Pradesh
Fetching 2025: Meerut Uttar Pradesh
Fetching 2025: Mirzapur Uttar Pradesh
Fetching 2025: Moradabad Uttar Pradesh
Fetching 2025: Muzaffarnagar Uttar Pradesh
Fetching 2025: Pilibhit Uttar Pradesh
Fetching 2025: Pratapgarh Uttar Pradesh
Fetching 2025: Prayagraj Uttar Pradesh
Fetching 2025: Rae Bareli Uttar Pradesh
Fetching 2025: Rampur Uttar Pradesh
Fetching 2025: Saharanpur Uttar Pradesh
Fetching 2025: Sambhal Uttar Pradesh
Fetching 2025: Sant Kabir Nagar Uttar Pradesh
Fetching 2025: Shahjahanpur Uttar Pradesh
Fetching 2025: Shamli Uttar Pradesh
Fetching 2025: Siddharthnagar Uttar Pradesh
Fetching 2025: Sitapur Uttar Pradesh
Fetching 2025: Sonbhadra Uttar Pradesh
Fetching 2025: Sultanpur Uttar Pradesh
Fetching 2025: Unnao Uttar Pradesh
Fetching 2025: Varanasi Uttar Pradesh

In [42]:
# Combine all rainfall

rainfall_daily_all = pd.concat(
    all_rainfall,
    ignore_index=True
)

rainfall_daily_all.head()

NameError: name 'all_rainfall' is not defined

In [43]:
rainfall_daily_all.shape

(175320, 7)

In [44]:
# Handling Nasa missing values

(rainfall_daily_all["Rainfall_mm"] == -999).sum()

np.int64(0)

In [45]:
rainfall_daily_all["Rainfall_mm"] = (
    rainfall_daily_all["Rainfall_mm"]
    .replace(-999, np.nan)
)

In [46]:
rainfall_daily_all[
    "Rainfall_mm"
].isnull().sum()

np.int64(0)

In [47]:
# Aggregating all districts annually

rainfall_history = (
    rainfall_daily_all
    .groupby(
        [
            "State",
            "District",
            "Year"
        ],
        as_index=False
    )
    .agg(
        Rainfall_mm=(
            "Rainfall_mm",
            "sum"
        ),
        Rainfall_Days_Available=(
            "Rainfall_mm",
            "count"
        )
    )
)

In [48]:
# Validating year completeness

pd.crosstab(
    rainfall_history["Year"],
    rainfall_history["State"]
)

State  Haryana  Punjab  Uttar Pradesh
Year
2021        22      23             75
2022        22      23             75
2023        22      23             75
2024        22      23             75

In [49]:
rainfall_history[
    "Rainfall_Days_Available"
].value_counts().sort_index()

Rainfall_Days_Available
365    360
366    120
Name: count, dtype: int64

In [50]:
# Saving rainfall dataset

rainfall_daily_all.to_csv(
    "../../data/processed/rainfall_daily_2021_2024.csv",
    index=False
)

In [51]:
#Saving annual rainfall dataset

rainfall_history.to_csv(
    "../../data/processed/rainfall_history_2021_2024.csv",
    index=False
)

In [52]:
problem_districts = [
    "Shahid Bhagat Singh Nagar",
    "Shrawasti"
]

districts[
    districts["District"].isin(problem_districts)
][
    [
        "State",
        "District",
        "Latitude",
        "Longitude",
        "Geocoded_Address"
    ]
]

,State,District,Latitude,Longitude,Geocoded_Address
42,Punjab,Shahid Bhagat Singh Nagar,NaN,NaN,NaN
113,Uttar Pradesh,Shrawasti,NaN,NaN,NaN

In [53]:
# Manually geocding sharwasti

shrawasti_location = geocode(
    "Shravasti district, Uttar Pradesh, India"
)

shrawasti_location

Location(Sravasti, Ikauna, Sharavasti, Uttar Pradesh, India, (27.5083429, 82.0263569, 0.0))

In [54]:
print(shrawasti_location.latitude)
print(shrawasti_location.longitude)
print(shrawasti_location.address)

27.5083429
82.0263569
Sravasti, Ikauna, Sharavasti, Uttar Pradesh, India

In [55]:
mask = (
    (districts["State"] == "Uttar Pradesh")
    &
    (districts["District"] == "Shrawasti")
)

districts.loc[
    mask,
    "Latitude"
] = shrawasti_location.latitude

districts.loc[
    mask,
    "Longitude"
] = shrawasti_location.longitude

districts.loc[
    mask,
    "Geocoded_Address"
] = shrawasti_location.address

In [56]:
districts[
    (districts["State"] == "Uttar Pradesh")
    &
    (districts["District"] == "Shrawasti")
]

,State,District,Latitude,Longitude,Geocoded_Address
113,Uttar Pradesh,Shrawasti,27.508343,82.026357,"Sravasti, Ikauna, Sharavasti, Uttar Pradesh, I..."

In [57]:
# Fixing the other district 

sbs_location = geocode(
    "Nawanshahr, Punjab, India"
)

sbs_location

Location(Shaheed Bhagat Singh Nagar, Punjab, India, (31.126969, 76.1598988, 0.0))

In [58]:
print(sbs_location.latitude)
print(sbs_location.longitude)
print(sbs_location.address)

31.126969
76.1598988
Shaheed Bhagat Singh Nagar, Punjab, India

In [59]:
mask = (
    (districts["State"] == "Punjab")
    &
    (
        districts["District"]
        == "Shahid Bhagat Singh Nagar"
    )
)

districts.loc[
    mask,
    "Latitude"
] = sbs_location.latitude

districts.loc[
    mask,
    "Longitude"
] = sbs_location.longitude

districts.loc[
    mask,
    "Geocoded_Address"
] = sbs_location.address

In [60]:
districts[
    districts["District"]
    == "Shahid Bhagat Singh Nagar"
]

,State,District,Latitude,Longitude,Geocoded_Address
42,Punjab,Shahid Bhagat Singh Nagar,31.126969,76.159899,"Shaheed Bhagat Singh Nagar, Punjab, India"

In [61]:
# Saving corrected coordinates

districts.to_csv(
    "../../data/processed/district_coordinates.csv",
    index=False
)

In [62]:
problem_coordinates = districts[
    districts["District"].isin(
        [
            "Shahid Bhagat Singh Nagar",
            "Shrawasti"
        ]
    )
]

problem_coordinates

,State,District,Latitude,Longitude,Geocoded_Address
42,Punjab,Shahid Bhagat Singh Nagar,31.126969,76.159899,"Shaheed Bhagat Singh Nagar, Punjab, India"
113,Uttar Pradesh,Shrawasti,27.508343,82.026357,"Sravasti, Ikauna, Sharavasti, Uttar Pradesh, I..."

In [67]:
missing_district_rainfall = []

for _, row in problem_coordinates.iterrows():

    print(
        "Fetching:",
        row["District"],
        row["State"]
    )

    result = fetch_nasa_rainfall(
        row["State"],
        row["District"],
        row["Latitude"],
        row["Longitude"],
        "20210101",
        "20241231"
    )

    if result is not None:
        missing_district_rainfall.append(result)

Fetching: Shahid Bhagat Singh Nagar Punjab
Fetching: Shrawasti Uttar Pradesh

In [68]:
missing_district_rainfall = pd.concat(
    missing_district_rainfall,
    ignore_index=True
)

In [69]:
rainfall_daily_all = pd.concat(
    [
        rainfall_daily_all,
        missing_district_rainfall
    ],
    ignore_index=True
)

In [70]:
rainfall_daily_all = (
    rainfall_daily_all
    .drop_duplicates(
        subset=[
            "State",
            "District",
            "Date"
        ]
    )
    .reset_index(drop=True)
)

In [71]:
rainfall_daily_all.to_csv(
    "../../data/processed/"
    "rainfall_daily_2021_2024.csv",
    index=False
)

In [72]:
# Combinig 2025 rainfall

rainfall_2025_part = pd.concat(
    rainfall_2025_part,
    ignore_index=True
)

In [73]:
rainfall_daily_extended = pd.concat(
    [
        rainfall_daily_all,
        rainfall_2025_part
    ],
    ignore_index=True
)

In [74]:
rainfall_daily_extended = (
    rainfall_daily_extended
    .drop_duplicates(
        subset=[
            "State",
            "District",
            "Date"
        ]
    )
    .sort_values(
        [
            "State",
            "District",
            "Date"
        ]
    )
    .reset_index(drop=True)
)

In [75]:

# Verifying the data range
rainfall_daily_extended["Date"].min()
rainfall_daily_extended["Date"].max()

Timestamp('2025-06-30 00:00:00')

In [76]:
print("Start:", rainfall_daily_extended["Date"].min())
print("End:", rainfall_daily_extended["Date"].max())

Start: 2021-01-01 00:00:00
End: 2025-06-30 00:00:00

In [77]:
rainfall_daily_extended.duplicated(
    subset=["State", "District", "Date"]
).sum()

np.int64(0)

In [78]:
rainfall_daily_extended.to_csv(
    "../../data/processed/rainfall_daily_2021_2025.csv",
    index=False
)